
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from './types';

// Use the values directly from the environment variables or fall back to the example values
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://zojeyhdebexjklkfdfxd.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvamV5aGRlYmV4amtsa2ZkZnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzIwNDEsImV4cCI6MjA2MDE0ODA0MX0.xrHPwGxIoJUR8DGHMOpUGvX8setvdPZK4c6oy1lWCZg';

// Remove the error check since we now have fallback values
// This prevents the app from crashing if environment variables are not set

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

// Helper function to handle Supabase errors
export function handleSupabaseError(error: unknown): never {
  if (error instanceof Error) {
    throw new Error(`Supabase error: ${error.message}`);
  }
  throw new Error('An unknown error occurred with Supabase');
}
